image:
  repository: us-central1-docker.pkg.dev/gcp-demo-project-471714/apps/backend
  tag: dev
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
