image:
  repository: us-central1-docker.pkg.dev/gcp-demo-project-471714/apps/frontend
  tag: dev
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
